### PR TITLE
Change throws Exception to more specific Exceptions

### PR DESCRIPTION
**Pull request by jonahgraham**
This pull request covers throwing more specific exceptions and catching them.

There are a few places where Exception is still caught in org.eclipse.dataset.impl.LazyDatasetBase and one place where Throwable is still caught in org.eclipse.dataset.metadata.Metadata.clone(). These should be reviewed too, but were not trivial, so I left them for the next round.

### CODE REVIEW

**Comment by jonahgraham** [comment]
PS, I can redo this code if it is of value to you, I thought it better to code my idea for exceptions.

**Comment by PeterC-DLS** [comment]
Looks fine. I was wondering about the RemoteDataset - is there a standard exception we can throw there? I will review that Metadata#clone() issue.

**Comment by jonahgraham** [comment]
I added some commits, including remerging this code to the master so it is clean to merge.

**Comment by jonahgraham** [comment]
> I was wondering about the RemoteDataset - is there a standard exception we can throw there? I will review that Metadata#clone() issue.

I don't think so. It may be better to add a new exception, something like RemoteDatasetException that extends DatasetException or IOException. The problem is that a RemoteDataset may (?) be over many types of links. e.g. over RMI a connection failure would be RemoteException, over Thrift it is a TException, etc.

BTW I note that IRemoteDataset has no implementation or references within the org.eclipse.dataset, so maybe postpone this until the whole remote dataset is ready to be included and delete IRemoteDataset for now.

**Pull request merged**
